### ISSUE TITLE
PHP 8.1 Roadmap

### ISSUE THREAD

**Issue by theofidry** [humbug/php-scoper#549]
Since it's been asked and because I don't really like GitHub projects I am posting this for providing more transparency.

- [x] [_In progress_] Remove `whitelist` keyword
  - [x] Add the expose keywords
  - [x] Leverage the expose keywords
  - [x] Completely remove the whitelist keyword
  - [x] Ensure the docs & template & template links are up to date
  - [x] Provide a migrate guide entry
- [x] Make the code PHP 8.1 compatible #543
- [x] Fix Box SerializablePhpScoper (more details in [571](https://github.com/box-project/box/issues/571))
- [x] Add support for PHP 8.1 features

Apart from the first issue, I think all other issues can be tackled by contributors so any help is welcomed there.
